### PR TITLE
Could not install from composer with Symfony bundle

### LINKED ISSUE #12: Could not install with composer
Trying to install the adapter through composer along with the symfony bundle gives me a error with php-translation/common.

I think the composer.json should be update to require ^1.0.0 instead of ^0.2.0 .

### PR DESCRIPTION
**Pull request by gaetan-petit**
Update dependencies to allow installing along the latest Symfony bundle.

Fixes: #12

### CODE REVIEW

**Comment by gaetan-petit** [comment]
Looks like there's things that should get fixed. I may look at it later.

**Comment by zairigimad** [comment]
this is Useful can this PR be merged :) ?

**Comment by welcoMattic** [comment]
New versions of php-translation package has been releases, could you update your PR? So, we will merge it :+1:

**Comment by gaetan-petit** [comment]
lol @welcoMattic it's been a full year since I opened those PRs.
Franckly nothing worked out of the box and noboby bothered to answer me.
I'll close my PRs, and I advised that you mark this project as unmainted.

**Comment by welcoMattic** [comment]
Hi @gaetan-petit, if you look around here, we are back to maintain this project, @Nyholm @odolbeau @bocharsky-bw @rvanlaak me and many other. You are very welcome to bring your help if you want. Be sure that we will take a look more regularly to every repositories of this organization.

**Comment by gaetan-petit** [comment]
@welcoMattic Nice to hear. Our main concern was that the adapter is assuming that you are using a fixed patter for translation keys. Which is quite problematic with existing application. see #16

**Pull request closed without merging**
